rbac:
  create: true
  serviceAccount:
    create: true
securityContext: null
sharedStorage:
  create: true
launcher:
  enabled: true
  useTemplates: true
  templateValues:
    service:
      type: ClusterIP
      annotations:
        five: six
    job:
      annotations:
        seven: eight
      labels:
        nine: ten
    pod:
      serviceAccountName: test
      annotations:
        one: two
      labels:
        three: four
      volumes:
        - name: test
          emptyDir: {}
      volumeMounts:
        - name: test
          mountPath: /tmp/mnt
      securityContext:
        runAsUser: 999
      nodeSelector:
        something: special
      priorityClassName: some-priority-class
      env:
        - name: key
          value: value
        - other: key2
          value: val2
      defaultSecurityContext:
        fsGroupChangePolicy: "Always"
        runAsGroup: 999
      containerSecurityContext:
        privileged: false
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.azure.com/scalesetpriority"
                    operator: In
                    values:
                      - "spot"
