rbac:
  create: true
  serviceAccount:
    create: true
securityContext: null
sharedStorage:
  create: true
launcher:
  enabled: true
  defaultInitContainer:
    enabled: true
    securityContext:
      allowPrivilegedEscalation: false
  additionalRuntimeImages: |
    - name: ghcr.io/rstudio/content-base:r4.1.0-py3.9.2-bionic
      python:
        installations:
          - path: /opt/python/3.9.2/bin/python3.9
            version: 3.9.2
      r:
        installations:
          - path: /opt/R/4.1.0/bin/R
            version: 4.1.0
  customRuntimeYaml: |
    name: Kubernetes
    images:
      -
        name: ghcr.io/rstudio/content-base:r3.1.3-py2.7.18-bionic
        python:
          installations:
            -
              path: /opt/python/2.7.18/bin/python2.7
              version: 2.7.18
        r:
          installations:
            -
              path: /opt/R/3.1.3/bin/R
              version: 3.1.3
