---
{{- if .Values.sealedSecret.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    {{- tpl ( toYaml .Values.sealedSecret.annotations ) . | nindent 4 }}
  name: {{ include "rstudio-workbench.fullname" . }}-secret
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    {{- include "rstudio-library.config.ini" .Values.config.secret | nindent 4 }}
    {{- /* do not auto-generate value as the secret will not be encrypted */}}
    {{- if .Values.launcherPem.existingSecret }}
    launcher.pem: |
      {{- $launcherPemSecret := (lookup "v1" "Secret" $.Release.Namespace .Values.launcherPem.existingSecret) }}
      {{- if $launcherPemSecret }}
      {{- $launcherPem := index $launcherPemSecret.data "private_key" | b64dec }}
      {{- $launcherPem | nindent 6 }}
      {{- end }}
    {{- else if .Values.launcherPem.value }}
    launcher.pem: |
      {{- .Values.launcherPem.value | nindent 6 }}
    {{- end}}
    {{- /* do not auto-generate value as the secret will not be encrypted */}}
    {{- if .Values.secureCookieKey.existingSecret }}
    secure-cookie-key: |
      {{- $secureCookieKeySecret := (lookup "v1" "Secret" $.Release.Namespace .Values.secureCookieKey.existingSecret) }}
      {{- if $secureCookieKeySecret }}
      {{- $secureCookieKey := index $secureCookieKeySecret.data "secure-cookie-key" | b64dec }}
      {{- $secureCookieKey | nindent 6 }}
      {{- end }}
    {{- else if .Values.secureCookieKey.value }}
    secure-cookie-key: |
      {{- .Values.secureCookieKey.value | nindent 6 }}
    {{- end}}
  template:
    data:
      {{- if .Values.launcherPub }}
      # TODO: would ideally be able to generate launcher.pub as well
      launcher.pub: |
        {{- .Values.launcherPub | nindent 8 }}
      {{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-secret
  namespace: {{ $.Release.Namespace }}
stringData:
  {{- include "rstudio-library.config.ini" .Values.config.secret | nindent 2 }}
  launcher.pem: |
    {{- include "rstudio-workbench.launcherPem" . | nindent 4 }}
  secure-cookie-key: |
    {{- include "rstudio-workbench.secureCookieKey" . | nindent 4 }}
  {{- if .Values.launcherPub }}
  # TODO: would ideally be able to generate launcher.pub as well
  launcher.pub: |
    {{- .Values.launcherPub | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.config.userProvisioning }}
{{- if .Values.sealedSecret.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    {{- tpl ( toYaml .Values.sealedSecret.annotations ) . | nindent 4 }}
  name: {{ include "rstudio-workbench.fullname" . }}-user
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    {{- include "rstudio-library.config.ini" .Values.config.userProvisioning | nindent 4 }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-user
  namespace: {{ $.Release.Namespace }}
stringData:
  {{- include "rstudio-library.config.ini" .Values.config.userProvisioning | nindent 2 }}
{{- end }}
{{- end }}
