apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-templates
  namespace: {{ $.Release.Namespace }}
data:
  rstudio-library-templates-data.tpl: |
    {{- $tplData := dict "name" "rstudio-library.templates.data" "value" .Values.config.sessionTemplate }}
    {{- include "rstudio-library.templates.dataOutput" $tplData | nindent 4}}
  service.tpl: |
    {{- include "rstudio-library.templates.service" nil | nindent 4 }}
  job.tpl: |
    {{- include "rstudio-library.templates.job" nil | nindent 4 }}
  test.txt: |
    {{- $templateData := include "rstudio-library.templates.data" nil | mustFromJson  -}}
    {{- $templateData | toYaml | nindent 4 }}
