{{/*
Test templates for rstudio-library license helpers.
Outputs license configuration to ConfigMaps/Secrets for testing.
*/}}

{{- if .Values.testLicense }}
{{- $licenseContext := dict
    "product" "test-product"
    "envVarPrefix" "TEST"
    "license" (dict
        "key" .Values.testLicense.licenseKey
        "server" .Values.testLicense.licenseServer
        "file" (dict
            "contents" .Values.testLicense.licenseFile
            "secret" ""
            "mountPath" "/etc/license"
            "secretKey" "license.lic"
            "mountSubPath" false
        )
    )
    "fullName" "test-release"
    "namespace" "test-namespace"
}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-license-env
  labels:
    {{- include "rstudio-library-test.labels" . | nindent 4 }}
data:
  env.yaml: |
    {{- include "rstudio-library.license-env" $licenseContext | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-license-mount
  labels:
    {{- include "rstudio-library-test.labels" . | nindent 4 }}
data:
  mount.yaml: |
    {{- include "rstudio-library.license-mount" $licenseContext | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-license-volume
  labels:
    {{- include "rstudio-library-test.labels" . | nindent 4 }}
data:
  volume.yaml: |
    {{- include "rstudio-library.license-volume" $licenseContext | nindent 4 }}
{{- /* License secret is a special case - it outputs actual Secret resources */}}
{{- include "rstudio-library.license-secret" $licenseContext }}
{{- end }}
