license:
  key: JWPY-WE3T-I29W-DDQ4-NVJQ-9NQG-GATA
# Configures user home directory shared storage
homeStorage:
  create: true
  mount: true
  storageClassName: freenas-nfs-csi # TODO: Change to a RWX StorageClass available in your cluster
  # volumeName: wb-home-pv-name # Only needed if PVs have been statically provisioned, in which case this will need to match the PV name.
  requests:
    storage: 100G

# Configures Workbench shared storage
sharedStorage:
  create: true
  mount: true
  storageClassName: freenas-nfs-csi # TODO: Change to a RWX StorageClass available in your cluster
  # volumeName: wb-shared-pv-name # Only needed if PVs have been statically provisioned, in which case this will need to match the PV name.
  requests:
    storage: 1G

service:
  type: ClusterIP
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: workbench-helm-k8s
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: "none"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"

launcher:
  useTemplates: true
  templateValues:
    pod:
      resources:
        requests:
          ephemeral-storage: "1Gi"
        limits:
          ephemeral-storage: "2Gi"
#       command:
#         - "/bin/bash"
#         - "-c"
#         - 'echo "Executing: /usr/lib/rstudio-server/bin/rserver-launcher $*" && /usr/bin/whoami && /usr/lib/rstudio-server/bin/rserver-launcher "$@"'
#         - "---"
#       volumes:
#         - name: shared-storage-pv
#           persistentVolumeClaim:
#             claimName: posit-workbench-test-shared-storage
#         - name: config-volume
#           configMap:
#             name: posit-workbench-test-config
#             items:
#             - key: vscode-user-settings.json
#               path: vscode-user-settings.json
#         - name: profile-script
#           configMap:
#             name: python-path-script
#             defaultMode: 0755
#       volumeMounts: 
#         - name: config-volume
#           mountPath: /etc/rstudio/vscode-user-settings.json
#           subPath: vscode-user-settings.json
#         - name: shared-storage-pv
#           mountPath: /var/lib/rstudio-servers/shared-storage
#         - name: profile-script
#           mountPath: /etc/profile.d/add-python-path.sh
#           subPath: add-python-path.sh
pod:
  hostAliases:
    - ip: 10.10.10.31
      hostnames:
        - "cofer.me"
  # sidecar:
  #   - name: test
  #     image: "busybox"
  #     imagePullPolicy: "IfNotPresent"
  #     command:
  #       - "sh"
  #       - "-c"
  #       - 'echo "Running sidecar test container" && sleep 3600'
  # volumes:
  # - name: profile-script
  #   configMap:
  #     name: python-path-script
  #     defaultMode: 0755
  # volumeMounts:
  # - name: profile-script
  #   mountPath: /etc/profile.d/add-python-path.sh
  #   subPath: add-python-path.sh

config:
  database:
    conf:
      value: |
        provider="postgresql"
        connection-uri="postgres://posit_team@posit-workbench-test1-postgresql:5432/posit_workbench?sslmode=disable"
        password=password
  server:
    logging.conf:
      "*":
        log-level: debug
        logger-type: file
    positron.conf:
      enabled: 1
      session-timeout-kill-hours: 12
      args: --host=0.0.0.0 --disable-workspace-trust
    rserver.conf:
      launcher-sessions-callback-address: https://workbench-test.local.cofer.me
      workbench-api-enabled: 1
      workbench-api-admin-enabled: 1
      workbench-api-super-admin-enabled: 1
      # auth-proxy: 1
      # auth-proxy-sign-in-url: https://adcli-joined-reverse-proxy-nginx.cofer.me/nginx-sign-in
      # auth-proxy-sign-in-delay: 5
      server-access-log: 1
      nginx-error-log-level: info
    vscode-user-settings.json: |
      {
          "terminal.integrated.shell.linux": "/bin/cow",
          "extensions.autoUpdate": false,
          "extensions.autoCheckUpdates": false,
          "terminal.integrated.profiles.linux": {
              "cow": {
                  "path": "/usr/bin/cow"
              }
          }
      }

    launcher.kubernetes.resources.conf:
      "default":
        cpus: "1.0"
        mem-mb: "2048"
      "small":
        cpus: "1.0"
        mem-mb: "512"
      "medium":
        cpus: "2.0"
        mem-mb: "4096"
      "large":
        cpus: "3.0"
        mem-mb: "8192"
    # logging.conf:
    #   "*":
    #     log-level: debug
    profiles:
      "*":
        session-limit: 5
        session-timeout-minutes: 60
    launcher-env: |
      ODBCSYSINI=/mnt/session-secret
  profiles:
      launcher.kubernetes.profiles.conf:
        "*":
          resource-profiles: default,small,medium,large
          default-cpus: 1
          default-mem-mb: 1024
  session:
      repos.conf:
          RSPM: https://packagemanager.posit.co/cran/__linux__/jammy/latest
          CRAN: https://packagemanager.posit.co/cran/__linux__/jammy/latest
      pip.conf: |
        [global]
        timeout = 60
        index-url = https://packagemanager.posit.co/pypi/latest/simple
      vscode.extensions.conf: |
        quarto.quarto
        REditorSupport.r@2.6.1
        ms-python.python
      vscode-user-settings.json: |
        {
            "terminal.integrated.shell.linux": "/bin/cow",
            "extensions.autoUpdate": false,
            "extensions.autoCheckUpdates": false,
            "terminal.integrated.profiles.linux": {
                "cow": {
                    "path": "/usr/bin/cow"
                }
            }
        }
  # secret:
    # database.conf:
    #   provider: "postgresql"
    #   connection-uri: "postgres://posit_team@posit-workbench-test1-postgresql:5432/posit_workbench?sslmode=disable" # TODO: Change this URI to reach your Postgres database.
    #   password: "password1"
  # TODO: Fill out the details of sssd.conf for your specific AD/LDAP setup. sssd is already present in the Workbench image.
  userProvisioning:
    sssd.conf:
      sssd:
        config_file_version: 2
        services: nss, pam
        domains: cofer.me
      domain/cofer.me:
        debug_level: 6
        id_provider: ldap
        auth_provider: ldap
        access_provider: permit
        enumerate: false
        cache_credentials: true
        ldap_schema: ad
        override_homedir: /home/%u
        ldap_group_name: cn
        ldap_tls_reqcert: never
        ldap_tls_cacert: /etc/ssl/certs/ca-certificates.crt
        # Define the bind DN for LDAP authentication
        ldap_default_bind_dn: CN=ldap-bind,CN=Users,DC=cofer,DC=me
        # ldap_default_authtok_type: password
        # ldap_default_authtok: uFPhX4-sC2=roq-
        ldap_default_authtok_type: obfuscated_password
        ldap_default_authtok: AAAgAFVppiyAnlPUOv/3gAnroX6z2rPW02JxWoVLqpmLtq1hCGgmmdG4Wt2VjkmBmY8CdHJga+EPxGZ4hDFYiRDiVLuaLHL3m2J/g10val2Ps165AAECAw==
        default_shell: /bin/bash
        ldap_id_mapping: True
        ldap_uri: ldap://cofer.me
        ldap_search_base: DC=cofer,DC=me
        ldap_user_search_base: OU=OU1,dc=cofer,dc=me???OU=OU2,dc=cofer,dc=me??
        #ldap_user_search_base: DC=cofer,DC=me
        ldap_id_use_start_tls: false
        ldap_auth_disable_tls_never_use_in_production: true

fullnameOverride: posit-workbench-test

extraObjects:
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: posit-workbench-test
    spec:
      entryPoints:
        - websecure
      routes:
      - kind: Rule
        match: (Host(`workbench-test.local.cofer.me`) || Host(`adcli-joined-reverse-proxy-nginx.cofer.me`)) && PathPrefix(`/metrics`)
        priority: 20
        services:
          - name: posit-workbench-test
            port: 8989

      # Route all other requests to port 80
      - kind: Rule
        match: Host(`workbench-test.local.cofer.me`) || Host(`adcli-joined-reverse-proxy-nginx.cofer.me`)
        priority: 10
        services:
          - name: posit-workbench-test
            port: 80
            sticky:
              cookie:
                httpOnly: true
                name: cookie
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: python-path-script
    data:
      add-python-path.sh: |
        #!/bin/bash
        export PATH=$PATH:/opt/python/3.11.10/bin