license:
  file:
    secret: posit-workbench-license
    secretKey: license.lic

replicas: 2

sharedStorage:
  create: true
  mount: true
  storageClassName: fsx-sc
  requests:
    storage: 1Gi # This is required to allow for a volume to be provisioned from FSx OpenZFS

homeStorage:
  create: true
  mount: true
  storageClassName: fsx-sc
  requests:
    storage: 1Gi # This is required to allow for a volume to be provisioned from FSx OpenZFS

ingress:
  enabled: true
  ingressClassName: "alb" # TODO: Fill in your desired ingressClassName for the ingress resource. If blank it will use the cluster default.
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/success-codes: 200,302,307
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400
    external-dns.alpha.kubernetes.io/hostname: workbench-sjc.soleng.posit.it #TODO: Replace with your domain
    external-dns.alpha.kubernetes.io/ttl: "15"

  hosts:
    - host: workbench-sjc.soleng.posit.it # TODO: Change to your domain
      paths:
        - "/" # TODO: Change to your desired path

# Creates the rstudio test user
userCreate: true

pod:
  env:
    - name: WORKBENCH_POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: workbench-db-sjc-app # This secret name is generated by the Postgres operator
          key: password 

launcher:
  useTemplates: true # Required when specifying custom PyPI repos in `pip.conf`

config:
  session:
    rsession.conf:
      default-rsconnect-server: "https://pub.current.posit.team/" # TODO: Add your Posit Connect URL to auto populate for users
      # These settings apply to RStudio Pro IDE sessions
      session-timeout-minutes: 60 # TODO: Adjust based on your requirements
      session-timeout-suspend: 1
      session-quit-child-processes-on-exit: 1
    repos.conf:
      # By default Posit Public Package Manager (P3M) is the default R 
      # repository for Workbench users. This is recommended as P3M provides
      # linux binaries for many R packages which will decrease package 
      # installation time. If you have your own Posit Package Manager server
      # then replace with the URL. Note you can list multiple repos in 
      # `repos.conf` but you must include one repo named "CRAN".
      CRAN: https://packagemanager.posit.co/cran/__linux__/jammy/latest # TODO: Change this URL to point to your own Package Manager CRAN URL if desired
    pip.conf:
      "global":
        index-url: https://packagemanager.posit.co/pypi/latest/simple # TODO: Change this URL to point to your own Package Manager PyPI URL if desired
        trusted-host: packagemanager.posit.co # TODO: Change this to match the domain name specified in `index-url`. Do NOT include http:// or https://
  server:
    rserver.conf:
      admin-enabled: 1 # More information at https://docs.posit.co/ide/server-pro/server_management/administrative_dashboard.html
      admin-group: "admingroup" # TODO: Specify Linux group(s) to give administrator privileges
      admin-superuser-group: "admin-superuser-group" # TODO: Specify Linux group(s) to give administrator superuser privileges
    jupyter.conf:
      # These settings apply to Jupyter Notebook and JupyterLab IDE sessions
      session-cull-minutes: 60 # TODO: Adjust based on your requirements
      session-shutdown-minutes: 5
  profiles:
    launcher.kubernetes.profiles.conf:
      "*": # TODO: Adjust based on your requirements
        # These settings are applied for all users and can be changed to suit
        # your particular user needs. See the following resources for more information:
        # https://github.com/rstudio/helm/tree/main/charts/rstudio-workbench#etcrstudiolauncherkubernetesprofilesconf
        # https://docs.posit.co/ide/server-pro/job_launcher/kubernetes_plugin.html#kube-profiles
        default-cpus: "1.0"
        default-mem-mb: "2048"
        max-cpus: "4.0"
        max-mem-mb: "8192"
  secret:
    database.conf:
      provider: "postgresql"
      connection-uri: "postgres://app@workbench-db-sjc-rw:5432/app?sslmode=require" 

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: posit-workbench-license # TODO: Change to the secret name in your cluster
    type: Opaque
    data:  ## TODO: Base64 encode your license file and paste it here!
      license.lic: LS0tLS1CRUdJTiBSU1RVRElPIExJQ0VOU0UtLS0tLQpEbWhjb2RRZlVTdHZuRVVCR3ZHNnZlQ2hRSFBRMUpuS04zcHNmdjh4RDM1MWRtelVNWFcvWWJWczJsOFAyRklKd1J5YVlHNCsKODRxTGVPR3ZtOUloS2g4cWtoUURIbU5QSldhZlNFTndaSldIQUVDRkZBQU4rL2pQa2txeEh3Z3VSWWtXS0tHQTUweEZnTUtwCkhua0hHTlJJODdBNFBvTUdLbWg1Zk84ZGhHMXMzdTVrSHI4N2R6MlIvcm43UUFJbGl3bnp3VlJGY0l2NFpFR3E0TlFTZGtXVwpncityY2l0eTFTN2VubXV4UEhjVjBhN2x5c0o0bVh3bzd5V2JDU2k2WjRUUmovMVg2R2QxT3pNVWEzS1BGd2dOMjZrbmd2Q3oKV2d2elR6TGhveXlaVVA0WHcxTzJ1UzV3UlowUkdlejRQN3h3aW54dHhTVFpPWG81WEhNOWpjOFJuWUJ5NFFFd3NleFUwclZsCmlPdTVYelFydzlXTmJVUFRZN0dCKzJhUEoweitzb0VtNDZXbnVuaDNSNmVCeldNOHcyakY0WXVpaVVuRzFEczRsMS80aXVHUwpINFd0OXUwRmZZUkNMSnNDTnJuZ3RWdVJRZDlEaERab3VaK3pGNHJDeFZuZStNYUhJcTVEcm15c1VncDNiN0lCMzNmOFdCcTEKdVhJR09IcmZIMWxLMWR2RGNGWFpNVjFVTGpYOUpDb0VBbzlRRnNtSUdmTWxSaHB2cUlrWWFZSW1NSEloZ1RRQ0RUcWV5R2kvCkJRT2FPOXJJRmtFZGxRMnNiWktJRXBYSStiUHFtQ01ldTltMk8wVC9WL3BaaGV4Mjd4Sjg4TjBKcTV6UWRxWmdLUXhUUlduYgpIQUdLVWRhcUpJellmUTY1T01NV2lVdTc4eEdVYm9JVktCSnZCbi9XaXRxQjVhR1hiL0hoK2RZWUhkMkNpQVg5U0d5RVVMdEkKVXVRSG1telVkL0VWcXJLUm5DYzNhdGVwcW9PL0d4bVdhVkR4WDNJYm9IUFJlTUV1WWl3SHR2MzVPMDRPS0ZzNXlUYjZhYkJtCjhOK0V5YUh2akZJeGNDbGZaSXZXeFcvVVY4VHJNaHJSdmllZmxkZzFWZEtyb0RGSXpnYWUwbjFsZXJvSk5SWFlFVWx6Yit3Two4SmdLa1luZndXQkZrM3pGSWZnT1I3TWFYZmdpbTBaOTBWSkVoVUdWRXJJWmFSR0ZzR3oxWEhsMkM0UlBweTFOQVFPWWNnTkcKQjBzPQotLS0tLUVORCBSU1RVRElPIExJQ0VOU0UtLS0tLQo=
  - apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: workbench-db-sjc
    spec:
      instances: 1
      storage:
        size: 1Gi