{{- $svcPort := .Values.service.port -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rstudio-pm.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "rstudio-pm.labels" . | nindent 4 }}
  annotations:
{{ include "rstudio-pm.annotations" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rstudio-pm.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    name: rspm
    port: {{ $svcPort }}
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    targetPort: 4242
---
