---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rstudio-pm.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "rstudio-pm.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
{{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  selector:
    {{- include "rstudio-pm.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    name: rspm
    port: {{ .Values.service.port }}
{{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
    targetPort: {{ .Values.service.targetPort }}
{{- if .Values.config.Metrics.Enabled }}
  - name: metrics
    port: 2112
{{- end }}
---
