ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik

  # Defines network routing in the traefik configuration.
  hosts:
    - host: connect.rstudio.com
      paths:
        - path: /test/
          pathType: Other
