rbac:
  create: true
  serviceAccount:
    create: true
securityContext: null
launcher:
  enabled: true
  customRuntimeYaml: |
    name: Kubernetes
    images:
      -
        name: ghcr.io/rstudio/content-base:r3.1.3-py2.7.18-bionic
        python:
          installations:
            -
              path: /opt/python/2.7.18/bin/python2.7
              version: 2.7.18
        r:
          installations:
            -
              path: /opt/R/3.1.3/bin/R
              version: 3.1.3
