name: rstudio-connect
description: Official Helm chart for Posit Connect
version: 0.20.0
apiVersion: v2
appVersion: 2026.04.1
icon: https://raw.githubusercontent.com/rstudio/helm/main/images/posit-icon-fullcolor.svg
home: https://posit.co
sources:
  - https://github.com/rstudio/helm
maintainers:
  - name: sol-eng
    email: docker@posit.co
    url: https://github.com/sol-eng
dependencies:
  - name: rstudio-library
    version: 0.1.36
    repository: https://helm.rstudio.com
annotations:
  artifacthub.io/images: |
    - name: connect
      image: posit/connect:2026.04.1-ubuntu-24.04
    - name: connect-content-init
      image: posit/connect-content-init:2026.04.1-ubuntu-24.04
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: About Connect
      url: https://posit.co/products/enterprise/connect/
    - name: Connect Documentation
      url: https://docs.posit.co/connect/
    - name: Posit Helm Documentation
      url: https://docs.posit.co/helm
    - name: Container Images
      url: https://github.com/posit-dev/images-connect
    - name: Posit Community Forum
      url: https://forum.posit.co/c/posit-professional-hosted
    - name: GitHub Discussions
      url: https://github.com/posit-dev/images/discussions
    - name: About Posit Team
      url: https://posit.co/products/enterprise/team/
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/rstudio/rstudio-workbench
    - url: https://artifacthub.io/packages/helm/rstudio/rstudio-pm
    - url: https://artifacthub.io/packages/helm/rstudio/posit-chronicle
keywords:
  - "data science"
  - "machine learning"
  - "r"
  - "rstats"
  - "python"
  - "deploy"
  - "rstudio"
  - "posit"
