name: Kubernetes
images:
  -
    name: posit/connect-content:R4.5.2-python3.14.3-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.5.2/bin/R
          version: 4.5.2
    python:
      installations:
        -
          path: /opt/python/3.14.3/bin/python3
          version: 3.14.3
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
  -
    name: posit/connect-content:R4.5.2-python3.13.12-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.5.2/bin/R
          version: 4.5.2
    python:
      installations:
        -
          path: /opt/python/3.13.12/bin/python3
          version: 3.13.12
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
  -
    name: posit/connect-content:R4.5.2-python3.12.12-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.5.2/bin/R
          version: 4.5.2
    python:
      installations:
        -
          path: /opt/python/3.12.12/bin/python3
          version: 3.12.12
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
  -
    name: posit/connect-content:R4.5.2-python3.11.14-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.5.2/bin/R
          version: 4.5.2
    python:
      installations:
        -
          path: /opt/python/3.11.14/bin/python3
          version: 3.11.14
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
  -
    name: posit/connect-content:R4.4.3-python3.14.3-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.4.3/bin/R
          version: 4.4.3
    python:
      installations:
        -
          path: /opt/python/3.14.3/bin/python3
          version: 3.14.3
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
  -
    name: posit/connect-content:R4.4.3-python3.13.12-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.4.3/bin/R
          version: 4.4.3
    python:
      installations:
        -
          path: /opt/python/3.13.12/bin/python3
          version: 3.13.12
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
  -
    name: posit/connect-content:R4.4.3-python3.12.12-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.4.3/bin/R
          version: 4.4.3
    python:
      installations:
        -
          path: /opt/python/3.12.12/bin/python3
          version: 3.12.12
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
  -
    name: posit/connect-content:R4.4.3-python3.11.14-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.4.3/bin/R
          version: 4.4.3
    python:
      installations:
        -
          path: /opt/python/3.11.14/bin/python3
          version: 3.11.14
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
  -
    name: posit/connect-content:R4.3.3-python3.14.3-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.3.3/bin/R
          version: 4.3.3
    python:
      installations:
        -
          path: /opt/python/3.14.3/bin/python3
          version: 3.14.3
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
  -
    name: posit/connect-content:R4.3.3-python3.13.12-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.3.3/bin/R
          version: 4.3.3
    python:
      installations:
        -
          path: /opt/python/3.13.12/bin/python3
          version: 3.13.12
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
  -
    name: posit/connect-content:R4.3.3-python3.12.12-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.3.3/bin/R
          version: 4.3.3
    python:
      installations:
        -
          path: /opt/python/3.12.12/bin/python3
          version: 3.12.12
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
  -
    name: posit/connect-content:R4.3.3-python3.11.14-ubuntu-24.04-pro
    r:
      installations:
        -
          path: /opt/R/4.3.3/bin/R
          version: 4.3.3
    python:
      installations:
        -
          path: /opt/python/3.11.14/bin/python3
          version: 3.11.14
    quarto:
      installations:
        - path: /opt/quarto/1.8.27/bin/quarto
          version: 1.8.27
