apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: connect-pvc
  namespace: connect-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: "5Gi"
