apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: connect-dev
servers: 1
agents: 0
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
ports:
  - port: 3939:30080
    nodeFilters:
      - server:*
