{{- if and (.Values.rbac.create) (or .Values.launcher.enabled .Values.kubernetes.enabled) }}
{{ $namespace := $.Release.Namespace }}
{{ $targetNamespace := $.Release.Namespace }}
{{- if .Values.launcher.enabled }}
{{ $targetNamespace = default $targetNamespace .Values.launcher.namespace }}
{{- else }}
{{ $targetNamespace = default $targetNamespace .Values.kubernetes.namespace }}
{{- end }}
{{ $serviceAccountName := default (include "rstudio-connect.fullname" .) .Values.rbac.serviceAccount.name }}
{{ $serviceAccountCreate := .Values.rbac.serviceAccount.create }}
{{ $serviceAccountAnnotations := .Values.rbac.serviceAccount.annotations }}
{{ $serviceAccountLabels := .Values.rbac.serviceAccount.labels }}
{{ $clusterRoleCreate := .Values.rbac.clusterRoleCreate }}
{{ $rbacValues1 := dict "namespace" $namespace "serviceAccountName" $serviceAccountName "targetNamespace" $targetNamespace }}
{{ $rbacValues2 := dict "serviceAccountCreate" $serviceAccountCreate "serviceAccountAnnotations" $serviceAccountAnnotations "serviceAccountLabels" $serviceAccountLabels }}
{{ $rbacValues3 := dict "clusterRoleCreate" $clusterRoleCreate }}
{{ $rbacValues := merge $rbacValues1 $rbacValues2 $rbacValues3 }}
{{ include "rstudio-library.rbac" $rbacValues }}
{{- end }}
