apiVersion: v2
name: rstudio-library-test
description: Test harness for rstudio-library templates
type: application
version: 0.1.0
appVersion: "0.1.0"

maintainers:
  - name: rstudio
    email: docker@posit.co
    url: https://github.com/rstudio/helm

dependencies:
  - name: rstudio-library
    version: ">= 0.1.0, < 1.0.0"
    repository: "file://../../charts/rstudio-library"
