---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "posit-chronicle.fullname" . }}
  namespace: {{ include "posit-chronicle.namespace" . }}
  labels:
    {{ include "posit-chronicle.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  posit-chronicle.gcfg: |
    {{- if .Values.config.HTTPS.Enabled }}
    [HTTPS]
    Listen = :443
    Certificate = {{ required ".Values.config.HTTPS.Certificate must be specified when .Values.config.HTTPS.Enabled is true." .Values.config.HTTPS.Certificate }}
    Key = {{ required ".Values.config.HTTPS.Key must be specified when .Values.config.HTTPS.Enabled is true." .Values.config.HTTPS.Key }}
    {{- else}}
    [HTTP]
    Listen = :5252
    {{- end }}

    [Logging]
    ServiceLog = {{ .Values.config.Logging.ServiceLog }}
    ServiceLogLevel = {{ .Values.config.Logging.ServiceLogLevel }}
    ServiceLogFormat = {{ .Values.config.Logging.ServiceLogFormat }}

    [Metrics]
    Enabled = {{ .Values.config.Metrics.Enabled }}

    [Profiling]
    Enabled = {{ .Values.config.Profiling.Enabled }}
    {{- if .Values.config.Profiling.Enabled }}
    Listen = :{{ .Values.config.Profiling.Port }}
    {{- end }}

    [LocalStorage]
    Enabled = {{ .Values.config.LocalStorage.Enabled }}
    {{- if .Values.config.LocalStorage.Enabled }}
    Location = {{ .Values.config.LocalStorage.Path }}
    {{- end }}

    [S3Storage]
    Enabled = {{ .Values.config.S3Storage.Enabled }}
    {{- if .Values.config.S3Storage.Enabled }}
    Bucket = {{ required "A .Values.config.S3Storage.Bucket must be specified when S3 storage is enabled." .Values.config.S3Storage.Bucket }}
    {{- if .Values.config.S3Storage.Prefix }}
    Prefix = {{ .Values.config.S3Storage.Prefix }}
    {{- end }}
    {{- if .Values.config.S3Storage.Profile }}
    Profile = {{ .Values.config.S3Storage.Profile }}
    {{- end }}
    {{- if .Values.config.S3Storage.Region }}
    Region = {{ .Values.config.S3Storage.Region }}
    {{- end }}
    {{- end }}
---
