{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "posit-chronicle.serviceAccountName" . }}
  namespace: {{ include "posit-chronicle.namespace" . }}
  labels:
    {{ include "posit-chronicle.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.serviceAccount.annotations .Values.commonAnnotations }}
  {{- $annotations := merge .Values.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- with $annotations }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
